package arep.crudsystem.model;

import jakarta.persistence.*;
import lombok.Data;

/**
 * Represents a property entity in the system.
 * This class is mapped to the "properties" table in the database.
 */
@Data
@Entity
@Table(name = "properties")
public class Property {
    /**
     * The unique identifier for the property.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The address of the property.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private String address;

    /**
     * The price of the property.
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private Double price;

    /**
     * The size of the property (e.g., in square meters).
     * This field is required and cannot be null.
     */
    @Column(nullable = false)
    private Double size;

    /**
     * A description of the property.
     * This field is optional.
     */
    @Column
    private String description;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Double getPrice() {
        return price;
    }

    public void setPrice(Double price) {
        this.price = price;
    }

    public Double getSize() {
        return size;
    }

    public void setSize(Double size) {
        this.size = size;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
